/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ReachRouteImport } from './routes/reach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteEducationRouteImport } from './routes/_site/education'
import { Route as SiteNewsRouteImport } from './routes/_site/news'
import { Route as SiteProcessRouteImport } from './routes/_site/process'
import { Route as SiteServicesRouteImport } from './routes/_site/services'
import { Route as SiteStudioRouteImport } from './routes/_site/studio'
import { Route as SiteTheGapRouteImport } from './routes/_site/the-gap'
import { Route as SiteWorkRouteImport } from './routes/_site/work'
import { Route as ApiPublicInquiryRouteImport } from './routes/api/public/inquiry'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEducationRoute = SiteEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewsRoute = SiteNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProcessRoute = SiteProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStudioRoute = SiteStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTheGapRoute = SiteTheGapRouteImport.update({
  id: '/the-gap',
  path: '/the-gap',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWorkRoute = SiteWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => SiteRoute,
} as any)
const ApiPublicInquiryRoute = ApiPublicInquiryRouteImport.update({
  id: '/api/public/inquiry',
  path: '/api/public/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/credits': typeof CreditsRoute
  '/reach': typeof ReachRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/education': typeof SiteEducationRoute
  '/news': typeof SiteNewsRoute
  '/process': typeof SiteProcessRoute
  '/services': typeof SiteServicesRoute
  '/studio': typeof SiteStudioRoute
  '/the-gap': typeof SiteTheGapRoute
  '/work': typeof SiteWorkRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRoutesByTo {
  '/credits': typeof CreditsRoute
  '/reach': typeof ReachRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/education': typeof SiteEducationRoute
  '/news': typeof SiteNewsRoute
  '/process': typeof SiteProcessRoute
  '/services': typeof SiteServicesRoute
  '/studio': typeof SiteStudioRoute
  '/the-gap': typeof SiteTheGapRoute
  '/work': typeof SiteWorkRoute
  '/': typeof SiteIndexRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/credits': typeof CreditsRoute
  '/reach': typeof ReachRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/education': typeof SiteEducationRoute
  '/_site/news': typeof SiteNewsRoute
  '/_site/process': typeof SiteProcessRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/studio': typeof SiteStudioRoute
  '/_site/the-gap': typeof SiteTheGapRoute
  '/_site/work': typeof SiteWorkRoute
  '/_site/': typeof SiteIndexRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/reach'
    | '/sitemap.xml'
    | '/who-we-are'
    | '/about'
    | '/contact'
    | '/education'
    | '/news'
    | '/process'
    | '/services'
    | '/studio'
    | '/the-gap'
    | '/work'
    | '/api/public/inquiry'
    | '/api/public/subscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/credits'
    | '/reach'
    | '/sitemap.xml'
    | '/who-we-are'
    | '/about'
    | '/contact'
    | '/education'
    | '/news'
    | '/process'
    | '/services'
    | '/studio'
    | '/the-gap'
    | '/work'
    | '/'
    | '/api/public/inquiry'
    | '/api/public/subscribe'
  id:
    | '__root__'
    | '/_site'
    | '/credits'
    | '/reach'
    | '/sitemap.xml'
    | '/who-we-are'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/education'
    | '/_site/news'
    | '/_site/process'
    | '/_site/services'
    | '/_site/studio'
    | '/_site/the-gap'
    | '/_site/work'
    | '/_site/'
    | '/api/public/inquiry'
    | '/api/public/subscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  ReachRoute: typeof ReachRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  ApiPublicInquiryRoute: typeof ApiPublicInquiryRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/education': {
      id: '/_site/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof SiteEducationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/news': {
      id: '/_site/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof SiteNewsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/process': {
      id: '/_site/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof SiteProcessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/studio': {
      id: '/_site/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof SiteStudioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/the-gap': {
      id: '/_site/the-gap'
      path: '/the-gap'
      fullPath: '/the-gap'
      preLoaderRoute: typeof SiteTheGapRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/work': {
      id: '/_site/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof SiteWorkRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/public/inquiry': {
      id: '/api/public/inquiry'
      path: '/api/public/inquiry'
      fullPath: '/api/public/inquiry'
      preLoaderRoute: typeof ApiPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteEducationRoute: typeof SiteEducationRoute
  SiteNewsRoute: typeof SiteNewsRoute
  SiteProcessRoute: typeof SiteProcessRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteStudioRoute: typeof SiteStudioRoute
  SiteTheGapRoute: typeof SiteTheGapRoute
  SiteWorkRoute: typeof SiteWorkRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteEducationRoute: SiteEducationRoute,
  SiteNewsRoute: SiteNewsRoute,
  SiteProcessRoute: SiteProcessRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteStudioRoute: SiteStudioRoute,
  SiteTheGapRoute: SiteTheGapRoute,
  SiteWorkRoute: SiteWorkRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  CreditsRoute: CreditsRoute,
  ReachRoute: ReachRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  ApiPublicInquiryRoute: ApiPublicInquiryRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
