/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as DoorsDraftRouteImport } from './routes/doors-draft'
import { Route as HierarchyOptionsRouteImport } from './routes/hierarchy-options'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ReachRouteImport } from './routes/reach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicInquiryRouteImport } from './routes/api/public/inquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsDraftRoute = DoorsDraftRouteImport.update({
  id: '/doors-draft',
  path: '/doors-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const HierarchyOptionsRoute = HierarchyOptionsRouteImport.update({
  id: '/hierarchy-options',
  path: '/hierarchy-options',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInquiryRoute = ApiPublicInquiryRouteImport.update({
  id: '/api/public/inquiry',
  path: '/api/public/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/doors-draft': typeof DoorsDraftRoute
  '/hierarchy-options': typeof HierarchyOptionsRoute
  '/mcp': typeof McpRoute
  '/process': typeof ProcessRoute
  '/reach': typeof ReachRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/doors-draft': typeof DoorsDraftRoute
  '/hierarchy-options': typeof HierarchyOptionsRoute
  '/mcp': typeof McpRoute
  '/process': typeof ProcessRoute
  '/reach': typeof ReachRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/doors-draft': typeof DoorsDraftRoute
  '/hierarchy-options': typeof HierarchyOptionsRoute
  '/mcp': typeof McpRoute
  '/process': typeof ProcessRoute
  '/reach': typeof ReachRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/credits'
    | '/doors-draft'
    | '/hierarchy-options'
    | '/mcp'
    | '/process'
    | '/reach'
    | '/sitemap.xml'
    | '/who-we-are'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/inquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/credits'
    | '/doors-draft'
    | '/hierarchy-options'
    | '/mcp'
    | '/process'
    | '/reach'
    | '/sitemap.xml'
    | '/who-we-are'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/inquiry'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/credits'
    | '/doors-draft'
    | '/hierarchy-options'
    | '/mcp'
    | '/process'
    | '/reach'
    | '/sitemap.xml'
    | '/who-we-are'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/inquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreditsRoute: typeof CreditsRoute
  DoorsDraftRoute: typeof DoorsDraftRoute
  HierarchyOptionsRoute: typeof HierarchyOptionsRoute
  McpRoute: typeof McpRoute
  ProcessRoute: typeof ProcessRoute
  ReachRoute: typeof ReachRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicInquiryRoute: typeof ApiPublicInquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors-draft': {
      id: '/doors-draft'
      path: '/doors-draft'
      fullPath: '/doors-draft'
      preLoaderRoute: typeof DoorsDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hierarchy-options': {
      id: '/hierarchy-options'
      path: '/hierarchy-options'
      fullPath: '/hierarchy-options'
      preLoaderRoute: typeof HierarchyOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiry': {
      id: '/api/public/inquiry'
      path: '/api/public/inquiry'
      fullPath: '/api/public/inquiry'
      preLoaderRoute: typeof ApiPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreditsRoute: CreditsRoute,
  DoorsDraftRoute: DoorsDraftRoute,
  HierarchyOptionsRoute: HierarchyOptionsRoute,
  McpRoute: McpRoute,
  ProcessRoute: ProcessRoute,
  ReachRoute: ReachRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicInquiryRoute: ApiPublicInquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
