export default `
<section class="page-hero"><div class="wrap"><div class="eyebrow">Start a project</div><h1 class="page-title">Tell me about the record.</h1><p class="page-deck">What you're making, where it is now, what's getting in the way. You don't need to know which service that is.</p></div></section>
<section class="section">
  <div class="wrap contact-grid">
    <aside class="contact-side reveal"><div class="kicker">Upper Level Music</div><h2>Start with the basics, not the booking language.</h2><p>A rough mix, voice memo, or private link is plenty. The form just gives me context to answer well.</p><div class="contact-direct"><a href="mailto:edwardlidow@upperlevelmusic.com">edwardlidow@upperlevelmusic.com</a><br>Columbia, South Carolina<br>By appointment · Remote work available</div><p class="contact-aside-note">Not a project? Questions, press, or just talking shop, the same address works.</p><div class="needs-content"><strong>Details needed</strong>Add a phone or text number, response time, and social links.</div></aside>
    <form class="form reveal" data-project-form>
      <div class="form-row"><div class="field"><label for="name">Name *</label><input id="name" name="name" required autocomplete="name"></div><div class="field"><label for="email">Email *</label><input id="email" name="email" type="email" required autocomplete="email"></div></div>
      <div class="field"><label for="details">What are you working on, and what's in the way? *</label><textarea id="details" name="details" required placeholder="What are you trying to make? What matters most? What feels wrong or unfinished right now? Plain language is fine."></textarea></div>
      <div class="field"><label for="links">Music / reference links</label><input id="links" name="links" type="url" inputmode="url" placeholder="Private streaming link, Drive, Dropbox, etc."></div>
      <div class="field"><label for="project">Artist / project name</label><input id="project" name="project" placeholder="Artist, band, project, or working title"></div>
      <div class="form-row"><div class="field"><label for="stage">Where is the project now?</label><select id="stage" name="stage"><option value="">Select one</option><option>Idea / writing stage</option><option>Demo or rough production</option><option>Tracking / recording</option><option>Vocals need work</option><option>Ready to mix</option><option>Mix is stuck</option><option>Ready for mastering</option><option>Technical / studio problem</option><option>Not sure yet</option></select></div><div class="field"><label for="need">Already know the service you need?</label><select id="need" name="need"><option value="">Not sure yet, that's fine</option><option>Production &amp; arrangement</option><option>Recording &amp; tracking</option><option>Vocal production &amp; editing</option><option>Mixing</option><option>Mastering</option><option>Full-project development</option><option>Consultation / problem-solving</option><option>Studio systems / signal flow</option><option>Voice / content audio</option><option>Teaching / mentoring</option></select></div></div>
      <div class="field"><label for="help">How would you rather work?</label><select id="help" name="help"><option value="">No preference</option><option>Just handle it for me</option><option>Work through it with me</option><option>Teach me how to do it</option><option>Not sure yet</option></select></div>
      <div class="form-row"><div class="field"><label for="timeline">Timeline</label><input id="timeline" name="timeline" placeholder="Target date or general timing"></div><div class="field"><label for="budget">Budget / range</label><input id="budget" name="budget" placeholder="A rough range is useful"></div></div>
      <div class="field" aria-hidden="true" style="position:absolute;left:-9999px;width:1px;height:1px;overflow:hidden"><label for="company">Company</label><input id="company" name="company" tabindex="-1" autocomplete="off"></div>
      <div class="form-actions"><button class="btn primary" type="submit">Send inquiry</button><div class="form-note">Sent straight to Edward. Replies go to the email you enter above.</div></div>
      <div class="form-status" data-form-status role="status" aria-live="polite"></div>
    </form>
  </div>
</section>
`;
